load compilers/gnu/7.3.0 environment
load cuda 10.0 environment
load python3 3.6.9 for Deep Learning environment (with numpy 1.15.1, Keras 2.2.5, scikit-learn 0.21.3, tensorflow-gpu 1.14.0, torch 1.2.0, more details: pip list)

Loading python3-DL/torch/1.2.0-cuda10
  Loading requirement: compilers/gnu/7.3.0 cuda/10.0
/var/spool/slurm/job8167341/slurm_script: line 61: python36/bin/activate: No such file or directory
/soft/Python3-DL1908/3.6.9/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/soft/Python3-DL1908/3.6.9/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/2017011/reljur01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type DataParallel. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/2017011/reljur01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type BB_Unet. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/2017011/reljur01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type DownConv. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/2017011/reljur01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type Conv2d. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/2017011/reljur01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type BatchNorm2d. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/2017011/reljur01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type Dropout2d. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/2017011/reljur01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type MaxPool2d. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/2017011/reljur01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type BBConv. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/2017011/reljur01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type UpConv. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/2017011/reljur01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type Upsample. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
Traceback (most recent call last):
  File "/home/2017011/reljur01/FBB_UNET/Train_Weakly.py", line 252, in <module>
    +1e-16 , 1e-16 )
  File "/home/2017011/reljur01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/torch/nn/functional.py", line 2009, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/2017011/reljur01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/torch/nn/functional.py", line 1848, in nll_loss
    out_size, target.size()))
ValueError: Expected target size (4, 320), got torch.Size([4, 320, 320])
